{application,myproj,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"myproj"},
              {modules,['Elixir.MyApp','Elixir.Twitter_Client',
                        'Elixir.Twitter_Misc',
                        'Elixir.Twitter_Server']},
              {registered,[]},
              {vsn,"0.1.0"},
              {error,{"no such file or directory","Elixir.Myproj.app"}},
              {mod,{'Elixir.MyApp',[]}}]}.
