{application,myproj,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"myproj"},
              {modules,['Elixir.MyApp','Elixir.TwitterClone.Client',
                        'Elixir.TwitterClone.Main',
                        'Elixir.TwitterClone.Server']},
              {registered,[]},
              {vsn,"0.1.0"},
              {error,{"no such file or directory","Elixir.Myproj.app"}},
              {mod,{'Elixir.MyApp',[]}}]}.
